name: jobfinder
description: "A new Flutter project."
 
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^5.8.0
  provider: ^6.0.4
  flutter_lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
